### ISSUE TITLE
There's slight offset in alignment in demo

### ISSUE THREAD

**Issue by jaypatelani** [reddec/element-logo-generator#1]
Here is screenshot to explain :

[![Screenshot-20200609-083111.jpg](https://i.postimg.cc/W1ZKHxpJ/Screenshot-20200609-083111.jpg)](https://postimg.cc/ZWTV97dT)

**Comment by reddec** [comment]
Thanks! But how did you reach it? (Chrome)
![Screenshot_2020-06-09-11-19-03-923_com android chrome](https://user-images.githubusercontent.com/6597086/84102459-1cbe8480-aa43-11ea-863c-69d7d05f83d1.jpg)

**Comment by jaypatelani** [comment]
I am on Android + Firefox .. just checked with chrome it works without error on chrome while firefox has offset
